const express = require('express')
const router = express.Router()

router.use('/admin/bot', require('./admin/bot-controller.js'))
router.use('/admin/customer-bots-chats', require('./admin/customer-bot-chat-controller.js'))
router.use('/admin/customer-bots', require('./admin/customer-bot-controller.js'))
router.use('/admin/customer', require('./admin/customer-controller.js'))
router.use('/admin/customer-event', require('./admin/customer-event-controller.js'))
router.use('/admin/email', require('./admin/email-controller.js'))
router.use('/admin/email-errors', require('./admin/email-error-controller.js'))
router.use('/admin/event-categories', require('./admin/event-category-controller.js'))
router.use('/admin/event-occurrences', require('./admin/event-occurrence-controller.js'))
router.use('/admin/prometer', require('./admin/prometer.js'))
router.use('/admin/prometer-spot', require('./admin/prometer-spot.js'))
router.use('/admin/send-emails', require('./admin/send-email-controller.js'))
router.use('/admin/spots', require('./admin/spot-controller.js'))
router.use('/admin/towns', require('./admin/town-controller.js'))
router.use('/admin/users', require('./admin/user-controller.js'))
router.use('/admin/faqs', require('./admin/faq-controller.js'))
router.use('/admin/feature-titles', require('./admin/feature-title-controller.js'))
router.use('/admin/heros', require('./admin/hero-controller.js'))

router.use('/customer/faqs', require('./customer/faq-controller.js'))
router.use('/customer/feature-titles', require('./customer/feature-title-controller.js'))
router.use('/customer/heros', require('./customer/hero-controller.js'))

module.exports = router
