const express = require('express')
const router = express.Router()

router.use('/admin/bots', require('./admin/bots.js'))
router.use('/admin/cards', require('./admin/cards.js'))
router.use('/admin/customer-bots', require('./admin/customer-bots.js'))
router.use('/admin/customer-events', require('./admin/customer-events.js'))
router.use('/admin/customer-credentials', require('./admin/customer-credentials.js'))
router.use('/admin/customers-bot-chats', require('./admin/customer-bot-chats.js'))
router.use('/admin/customers', require('./admin/customers.js'))
router.use('/admin/email-errors', require('./admin/email-errors.js'))
router.use('/admin/emails', require('./admin/email.js'))
router.use('/admin/event-categories', require('./admin/event-categories.js'))
router.use('/admin/event-occurrences', require('./admin/event-occurrences.js'))
router.use('/admin/faqs', require('./admin/faqs.js'))
router.use('/admin/feature-titles', require('./admin/feature-titles.js'))
router.use('/admin/heros', require('./admin/heros.js'))
router.use('/admin/languages', require('./admin/languages.js'))
router.use('/admin/promoter-spots', require('./admin/promoter-spots.js'))
router.use('/admin/promoters', require('./admin/promoters.js'))
router.use('/admin/subscription-forms', require('./admin/subscription-forms.js'))
router.use('/admin/sent-emails', require('./admin/sent-email.js'))
router.use('/admin/spots', require('./admin/spots.js'))
router.use('/admin/towns', require('./admin/towns.js'))
router.use('/admin/user-credentials', require('./admin/user-credentials.js'))
router.use('/admin/users', require('./admin/users.js'))

router.use('/auth', require('./auth/auth-activate.js'))
router.use('/auth/customer', require('./auth/auth-customers.js'))
router.use('/auth/user', require('./auth/auth-users.js'))

router.use('/customer/cards', require('./customer/cards.js'))
router.use('/customer/chats', require('./customer/chats.js'))
router.use('/customer/customers', require('./customer/customers.js'))
router.use('/customer/faqs', require('./customer/faqs.js'))
router.use('/customer/feature-titles', require('./customer/feature-titles.js'))
router.use('/customer/heros', require('./customer/heros.js'))

module.exports = router
