const express = require('express')
const router = express.Router()

router.use('/admin/bots', require('./admin/bots.js'))
router.use('/admin/cards', require('./admin/cards.js'))
router.use('/admin/customer-bots', require('./admin/customer-bots.js'))
router.use('/admin/customer-events', require('./admin/customer-events.js'))
router.use('/admin/customers', require('./admin/customers.js'))
router.use('/admin/customers-bot-chats', require('./admin/customer-bot-chats.js'))
router.use('/admin/email-errors', require('./admin/email-errors.js'))
router.use('/admin/emails', require('./admin/email.js'))
router.use('/admin/event-categories', require('./admin/event-categories.js'))
router.use('/admin/event-occurrences', require('./admin/event-occurrences.js'))
router.use('/admin/faqs', require('./admin/faqs.js'))
router.use('/admin/feature-titles', require('./admin/feature-titles.js'))
router.use('/admin/heros', require('./admin/heros.js'))
router.use('/admin/images', require('./admin/images.js'))
router.use('/admin/menus', require('./admin/menus.js'))
router.use('/admin/menu-items', require('./admin/menu-items.js'))
router.use('/admin/promoter-spots', require('./admin/promoter-spots.js'))
router.use('/admin/promoters', require('./admin/promoters.js'))
router.use('/admin/sent-emails', require('./admin/sent-email.js'))
router.use('/admin/spots', require('./admin/spots.js'))
router.use('/admin/towns', require('./admin/town.js'))
router.use('/admin/users', require('./admin/users.js'))

router.use('/customer/cards', require('./customer/cards.js'))
router.use('/customer/chats', require('./customer/chats.js'))
router.use('/customer/customers', require('./customer/customers.js'))
router.use('/customer/faqs', require('./customer/faqs.js'))
router.use('/customer/feature-titles', require('./customer/feature-titles.js'))
router.use('/customer/heros', require('./customer/heros.js'))
router.use('/customer/images', require('./customer/images.js'))
router.use('/customer/properties', require('./customer/properties'))
router.use('/customer/search', require('./customer/search.js'))

module.exports = router
